### ISSUE TITLE
Training on 1024 resolution

### ISSUE THREAD

**Issue by piddnad** [rosinality/alias-free-gan-pytorch#20]
Hello, thanks for your great work.

I tried to train alias-free gan with [config-t](https://github.com/rosinality/alias-free-gan-pytorch/blob/main/config/config-t.jsonnet) on the resolution of 1024, by **simply editing training.size to 1024 in the config file**, but the network seems not converge and the generated result is not good either.

Do I need to modify some other arguments for training on a larger resolution (e.g. 512, 1024)?

Thanks!

**Comment by rosinality** [comment]
You can may try to increase channel_base to std.pow(2, 15) and r1 regularization to 32.8, as noted in the paper.

**Comment by piddnad** [comment]
I see, and I will try it out. Thank you for your reply!

**Comment by budui** [comment]
Hi~, Did you get any meaningful results from your training at the 512/1024 scale? The results I got from my training(size=512, channel_base=2**15, R1=1 or 10) showed the mode collapse like this:

![image](https://user-images.githubusercontent.com/16448529/130320413-8f267562-dd86-47d5-9d67-dd72b66a7118.png)

**Comment by MHRosenberg** [comment]
Hi @budui, I'm currently trying to train on 1024 x 1024 px images and the model seems to occupy about 15GB of memory on my GPU. Do you see something similar when training with your images. If so, did you take any measures to reduce the size of the model?

**Comment by budui** [comment]
Below is the log related to my training of a 512 resolution generator.

```text
2021-08-26 00:51:40.035 | DEBUG    | training.helper:log_message:227 - [24999/25000] | run_time: 2 days, 6:22:00 | remain: 0:00:00 | tick_time: 13.55s | gpu_mem: 20.26 GB | speed: 13.23 s/kimg
2021-08-26 00:51:53.582 | DEBUG    | training.engine.StyleGAN2:cal_fid:387 - begin to calculate fid
2021-08-26 00:54:29.115 | INFO     | training.engine.StyleGAN2:cal_fid:389 - fid is 9.927520871987948 when 25600 kimg
```

```yaml
model:
  generator:
    _type: AliasFree-Generator
    size: 512
    n_mlp: 2
    channel_base: 16384
    num_fp16_layers: 4
    conv_clamp: 256.0
    style_dim: 512
  discriminator:
    _type: StyleGAN2-Discriminator-mine
    size: 512
    channel_multiplier: 2
    stddev_group: 4
    num_fp16_res: 4
    conv_clamp: 256.0
train:
  runner: StyleGAN2
  num_real_images: 25600000
  latent_mixing: 0
  batch_size_base: 32
  ema:
    num_images_of_half_life: 10000
    rampup: null
  lazy_regularization:
    interval:
      generator: 1
      discriminator: 16
  optimizer:
    generator:
      _type: Adam
      lr: 0.003
      betas:
      - 0
      - 0.99
    discriminator:
      _type: Adam
      lr: 0.002
      betas:
      - 0
      - 0.99
  loss:
    r1:
      weight: 10
    path_length_regularization:
      weight: 0
      batch_shrink: 2
      decay: 0.01
  augment:
    enable: false
```


I am now using my own training framework and rosinality's model implementation. In addition to this, I have also implemented mixed precision training with reference to stylegan2-ada-pytorch. I am now using 8*V100(32GB) and have not reduce the size of the model, so my train details may not be worth referencing. This work was done during my internship and so I'm sorry I can't share the code.
